### ISSUE TITLE
got error when mutating .sol file

### ISSUE THREAD

**Issue by erfanwakka** [agroce/universalmutator#1]
I got this error when try to mutate a solidity contract. please help me 

```
*** UNIVERSALMUTATOR ***
MUTATING WITH RULES: universal.rules, solidity.rules, c_like.rules
152 MUTANTS GENERATED BY RULES
Traceback (most recent call last):
  File "/usr/local/bin/mutate", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/universalmutator/genmutants.py", line 306, in main
    mutantResult = handler(tmpMutantName, mutant, sourceFile, uniqueMutants)
  File "/usr/local/lib/python2.7/site-packages/universalmutator/solidity_handler.py", line 32, in handler
    ["solc", compileFile, "--asm", "--optimize"], stdout=file, stderr=file)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by agroce** [comment]
You need to install the solc compiler, and have it in your path.

**Comment by erfanwakka** [comment]
Thanks that solve my error. But now I have another issue. I don't know why all the mutant that produced my universalmutator is invalid for smart contract. even swapping code !!!. below are some mutant that said to be INVALID!! but I think they are valid.


```
PROCESSING MUTANT: 16:   int x,y;  ==>    int x,y;
  break;...INVALID
TRYING CODE SWAPS...
TRYING TO SWAP LINES 1 AND 2...INVALID
TRYING TO SWAP LINES 2 AND 3...INVALID
TRYING TO SWAP LINES 3 AND 4...INVALID
TRYING TO SWAP LINES 4 AND 5...INVALID
PROCESSING MUTANT: 13:       x = 22;  ==>        x = (22+1);...INVALID
PROCESSING MUTANT: 13:       x = 22;  ==>        x = (22-1);...INVALID
```

**Comment by agroce** [comment]
If you compile your contract with `solc`, what does it say?

At a command line type:

```
solc mycontractname.sol
```

Does it report any errors?  The mutation engine requires that your original contract compile without errors, it uses errors to prune out invalid mutants.  Usually no valid mutants means your original code isn't valid either.

**Comment by erfanwakka** [comment]
Thanks a lot. you are a saviour :)
